// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15eOfUeBeMhxiEjb0FNENC2nTIqlgSME',
    appId: '1:760559603221:web:bfac32af5d166c1444081c',
    messagingSenderId: '760559603221',
    projectId: 'instagram-93c56',
    authDomain: 'instagram-93c56.firebaseapp.com',
    storageBucket: 'instagram-93c56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk6nGA_sXaYuFm8xcHuMNKDNj3YXaVSNs',
    appId: '1:760559603221:android:4fe8c2747e4d87c544081c',
    messagingSenderId: '760559603221',
    projectId: 'instagram-93c56',
    storageBucket: 'instagram-93c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUVFDsg5LVn-w9zzee2EWfjEk-16xRs5s',
    appId: '1:760559603221:ios:4a59478e4232c04f44081c',
    messagingSenderId: '760559603221',
    projectId: 'instagram-93c56',
    storageBucket: 'instagram-93c56.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUVFDsg5LVn-w9zzee2EWfjEk-16xRs5s',
    appId: '1:760559603221:ios:4a59478e4232c04f44081c',
    messagingSenderId: '760559603221',
    projectId: 'instagram-93c56',
    storageBucket: 'instagram-93c56.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC15eOfUeBeMhxiEjb0FNENC2nTIqlgSME',
    appId: '1:760559603221:web:3afe0a6886498bbc44081c',
    messagingSenderId: '760559603221',
    projectId: 'instagram-93c56',
    authDomain: 'instagram-93c56.firebaseapp.com',
    storageBucket: 'instagram-93c56.appspot.com',
  );
}
